In [1]:
import pandas as pd

In [2]:
dataset_url = "https://raw.githubusercontent.com/OpenClassrooms-Student-Center/8063076-Initiez-vous-au-Machine-Learning/refs/heads/master/data/ADEME_dpe-v2-tertiaire-2.csv"
df = pd.read_csv(dataset_url)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 63 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   N°DPE                              10000 non-null  str
 1   Date_réception_DPE                 10000 non-null  str
 2   Date_établissement_DPE             10000 non-null  str
 3   Date_visite_diagnostiqueur         10000 non-null  str
 4   Modèle_DPE                         10000 non-null  str
 5   N°_DPE_remplacé                    582 non-null    str
 6   Date_fin_validité_DPE              10000 non-null  str
 7   Version_DPE                        10000 non-null  float64
 8   N°_DPE_immeuble_associé            26 non-null     str
 9   Méthode_du_DPE                     9585 non-null   str
 10  N°_immatriculation_copropriété     34 non-null     str
 11  Invariant_fiscal_logement          60 non-null     str
 12  Etiquette_DPE                      5608 non-null   str
 13  Etiquette_GES                      5608 non-null   str
 14  Conso_kWhep/m²/an                  5608 non-null   float64
 15  Emission_GES_kgCO2/m²/an           5608 non-null   float64
 16  Année_construction                 6581 non-null   float64
 17  Catégorie_ERP                      7794 non-null   str
 18  Période_construction               10000 non-null  str
 19  Secteur_activité                   10000 non-null  str
 20  Nombre_occupant                    9455 non-null   float64
 21  Surface_(SHON)                     8056 non-null   float64
 22  Surface_utile                      10000 non-null  float64
 23  Type_énergie_principale_chauffage  1027 non-null   str
 24  Adresse_brute                      9997 non-null   str
 25  Nom__commune_(BAN)                 9975 non-null   str
 26  Code_INSEE_(BAN)                   9975 non-null   str
 27  N°_voie_(BAN)                      8049 non-null   str
 28  Identifiant__BAN                   9975 non-null   str
 29  Adresse_(BAN)                      9975 non-null   str
 30  Code_postal_(BAN)                  9975 non-null   float64
 31  Score_BAN                          9975 non-null   float64
 32  Nom__rue_(BAN)                     8864 non-null   str
 33  Coordonnée_cartographique_X_(BAN)  9975 non-null   float64
 34  Coordonnée_cartographique_Y_(BAN)  9975 non-null   float64
 35  Code_postal_(brut)                 10000 non-null  int64
 36  N°_étage_appartement               7107 non-null   float64
 37  Nom_résidence                      935 non-null    str
 38  Complément_d'adresse_bâtiment      3724 non-null   str
 39  Cage_d'escalier                    74 non-null     str
 40  Complément_d'adresse_logement      3640 non-null   str
 41  Statut_géocodage                   10000 non-null  str
 42  Nom__commune_(Brut)                9999 non-null   str
 43  N°_département_(BAN)               9963 non-null   str
 44  N°_région_(BAN)                    9963 non-null   float64
 45  Conso_é_finale_énergie_n°1         5552 non-null   float64
 46  Conso_é_primaire_énergie_n°1       5552 non-null   float64
 47  Type_énergie_n°1                   5552 non-null   str
 48  Type_usage_énergie_n°1             5552 non-null   str
 49  Frais_annuel_énergie_n°1           5552 non-null   float64
 50  Année_relève_conso_énergie_n°1     4952 non-null   float64
 51  Conso_é_finale_énergie_n°2         2161 non-null   float64
 52  Conso_é_primaire_énergie_n°2       2161 non-null   float64
 53  Type_énergie_n°2                   2161 non-null   str
 54  Type_usage_énergie_n°2             2161 non-null   str
 55  Frais_annuel_énergie_n°2           2161 non-null   float64
 56  Année_relève_conso_énergie_n°2     1952 non-null   float64
 57  Conso_é_finale_énergie_n°3         881 non-null    float64
 58  Conso_é_primaire_énergie_n°3       881 non-null    float64
 59  Type_énergie_n°3                   881 non-null    str
 60  Type_usage_énergie_n°3             881 non-null    str
 61  Frais_annuel_énergie_n°3           881 non-null    float64
 62  Année_relève_conso_énergie_n°3     749 non-null    float64
dtypes: float64(25), int64(1), str(37)
memory usage: 4.8 MB

In [4]:
df.columns

Index(['N°DPE', 'Date_réception_DPE', 'Date_établissement_DPE',
       'Date_visite_diagnostiqueur', 'Modèle_DPE', 'N°_DPE_remplacé',
       'Date_fin_validité_DPE', 'Version_DPE', 'N°_DPE_immeuble_associé',
       'Méthode_du_DPE', 'N°_immatriculation_copropriété',
       'Invariant_fiscal_logement', 'Etiquette_DPE', 'Etiquette_GES',
       'Conso_kWhep/m²/an', 'Emission_GES_kgCO2/m²/an', 'Année_construction',
       'Catégorie_ERP', 'Période_construction', 'Secteur_activité',
       'Nombre_occupant', 'Surface_(SHON)', 'Surface_utile',
       'Type_énergie_principale_chauffage', 'Adresse_brute',
       'Nom__commune_(BAN)', 'Code_INSEE_(BAN)', 'N°_voie_(BAN)',
       'Identifiant__BAN', 'Adresse_(BAN)', 'Code_postal_(BAN)', 'Score_BAN',
       'Nom__rue_(BAN)', 'Coordonnée_cartographique_X_(BAN)',
       'Coordonnée_cartographique_Y_(BAN)', 'Code_postal_(brut)',
       'N°_étage_appartement', 'Nom_résidence',
       'Complément_d'adresse_bâtiment', 'Cage_d'escalier',
       'Complément_d'adresse_logement', 'Statut_géocodage',
       'Nom__commune_(Brut)', 'N°_département_(BAN)', 'N°_région_(BAN)',
       'Conso_é_finale_énergie_n°1', 'Conso_é_primaire_énergie_n°1',
       'Type_énergie_n°1', 'Type_usage_énergie_n°1',
       'Frais_annuel_énergie_n°1', 'Année_relève_conso_énergie_n°1',
       'Conso_é_finale_énergie_n°2', 'Conso_é_primaire_énergie_n°2',
       'Type_énergie_n°2', 'Type_usage_énergie_n°2',
       'Frais_annuel_énergie_n°2', 'Année_relève_conso_énergie_n°2',
       'Conso_é_finale_énergie_n°3', 'Conso_é_primaire_énergie_n°3',
       'Type_énergie_n°3', 'Type_usage_énergie_n°3',
       'Frais_annuel_énergie_n°3', 'Année_relève_conso_énergie_n°3'],
      dtype='str')

In [6]:
missing = pd.DataFrame({
    "nb_nan": df.isna().sum(),
    "pct_nan": df.isna().mean() * 100
}).sort_values(by="pct_nan", ascending=False)

missing.head(20)

                                   nb_nan  pct_nan
N°_DPE_immeuble_associé              9974    99.74
N°_immatriculation_copropriété       9966    99.66
Invariant_fiscal_logement            9940    99.40
Cage_d'escalier                      9926    99.26
N°_DPE_remplacé                      9418    94.18
Année_relève_conso_énergie_n°3       9251    92.51
Type_usage_énergie_n°3               9119    91.19
Frais_annuel_énergie_n°3             9119    91.19
Conso_é_finale_énergie_n°3           9119    91.19
Conso_é_primaire_énergie_n°3         9119    91.19
Type_énergie_n°3                     9119    91.19
Nom_résidence                        9065    90.65
Type_énergie_principale_chauffage    8973    89.73
Année_relève_conso_énergie_n°2       8048    80.48
Type_usage_énergie_n°2               7839    78.39
Conso_é_finale_énergie_n°2           7839    78.39
Conso_é_primaire_énergie_n°2         7839    78.39
Type_énergie_n°2                     7839    78.39
Frais_annuel_énergie_n°2             7839    78.39
Complément_d'adresse_logement        6360    63.60

In [8]:
df.describe()

,Version_DPE,Conso_kWhep/m²/an,Emission_GES_kgCO2/m²/an,Année_construction,Nombre_occupant,Surface_(SHON),Surface_utile,Code_postal_(BAN),Score_BAN,Coordonnée_cartographique_X_(BAN),...,Frais_annuel_énergie_n°1,Année_relève_conso_énergie_n°1,Conso_é_finale_énergie_n°2,Conso_é_primaire_énergie_n°2,Frais_annuel_énergie_n°2,Année_relève_conso_énergie_n°2,Conso_é_finale_énergie_n°3,Conso_é_primaire_énergie_n°3,Frais_annuel_énergie_n°3,Année_relève_conso_énergie_n°3
count,10000.000000,5608.000000,5608.000000,6581.000000,9.455000e+03,8056.000000,10000.000000,9975.000000,9975.000000,9.975000e+03,...,5.552000e+03,4.952000e+03,2.161000e+03,2.161000e+03,2.161000e+03,1.952000e+03,8.810000e+02,8.810000e+02,8.810000e+02,749.000000
mean,1.983680,292.195043,16.938017,1967.796687,3.122633e+04,688.102644,423.974620,53439.532231,0.671730,6.768906e+05,...,3.866860e+05,1.515523e+04,1.249748e+05,1.738170e+05,9.779239e+04,2.069791e+04,1.277058e+05,2.395632e+05,8.228194e+07,2007.189586
std,0.402263,1536.982083,55.627943,36.271297,3.011636e+06,3872.377331,2524.285877,26499.167007,0.165131,2.057973e+05,...,1.197872e+07,5.004406e+05,4.640727e+05,8.278393e+05,3.308779e+06,5.000095e+05,4.799498e+05,1.047240e+06,2.441765e+09,164.661105
min,1.000000,-67.000000,0.000000,1300.000000,0.000000e+00,0.900000,2.400000,1000.000000,0.120000,1.289436e+05,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,2.100000,103.200000,3.500000,1947.000000,0.000000e+00,60.975000,100.000000,32125.000000,0.550000,5.612393e+05,...,8.315000e+02,2.021000e+03,5.550000e+03,5.225200e+03,7.890000e+02,2.020000e+03,5.017000e+03,6.555000e+03,7.140000e+02,2020.000000
50%,2.100000,198.400000,8.000000,1970.000000,1.000000e+00,121.250000,100.000000,57970.000000,0.660000,6.570308e+05,...,2.394300e+03,2.022000e+03,1.721300e+04,1.918890e+04,2.231000e+03,2.021000e+03,1.500800e+04,2.445080e+04,2.113300e+03,2021.000000
75%,2.200000,330.500000,19.800000,1996.000000,6.850000e+01,324.050000,100.000000,75012.000000,0.790000,8.432618e+05,...,7.337875e+03,2.022000e+03,6.138640e+04,6.718500e+04,7.293300e+03,2.022000e+03,5.093500e+04,8.713780e+04,6.417000e+03,2022.000000
max,2.300000,112336.300000,3125.900000,2023.000000,2.928417e+08,166771.000000,116912.000000,97470.000000,0.990000,1.237998e+06,...,5.833511e+08,2.021202e+07,6.884830e+06,1.583511e+07,1.528298e+08,1.503202e+07,6.482042e+06,1.490870e+07,7.247561e+10,2026.000000

In [9]:
df[df['Année_construction'] == 1300]

,N°DPE,Date_réception_DPE,Date_établissement_DPE,Date_visite_diagnostiqueur,Modèle_DPE,N°_DPE_remplacé,Date_fin_validité_DPE,Version_DPE,N°_DPE_immeuble_associé,Méthode_du_DPE,...,Type_énergie_n°2,Type_usage_énergie_n°2,Frais_annuel_énergie_n°2,Année_relève_conso_énergie_n°2,Conso_é_finale_énergie_n°3,Conso_é_primaire_énergie_n°3,Type_énergie_n°3,Type_usage_énergie_n°3,Frais_annuel_énergie_n°3,Année_relève_conso_énergie_n°3
6302,2207T0736604V,2022-04-08,2022-04-08,2021-10-07,DPE 2006 tertiaire et ERP,NaN,2032-04-07,2.0,NaN,dpe tertiaire vierge,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
col = 'Emission_GES_kgCO2/m²/an'
df = df[~df[col].isna()].copy()
df.reset_index(inplace = True, drop = True)

In [12]:
df['Emission_GES_kgCO2/m²/an'].notna().sum()

np.int64(5608)

In [16]:
from scipy import stats

col = 'Emission_GES_kgCO2/m²/an'

# seuil 3
df_z3 = df[df['z_emissions'].abs() <= 3]
nb_supprimes_3 = len(df) - len(df_z3)

# seuil 2
df_z2 = df[df['z_emissions'].abs() <= 2]
nb_supprimes_2 = len(df) - len(df_z2)
print(f"  Supprimés : {nb_supprimes_3}")
print(f"  Supprimés : {nb_supprimes_2}")

  Supprimés : 11
  Supprimés : 37

In [24]:
import numpy as np

col = 'Emission_GES_kgCO2/m²/an'

data = df[col].dropna()


# Calcul des quantiles
q1 = np.quantile(df[col], 0.25)
q3 = np.quantile(df[col], 0.75)

# Calcul IQR
iqr = q3 - q1

# Bornes
borne_basse = q1 - 1.5 * iqr
borne_haute = q3 + 1.5 * iqr

# Affichage
print("=== IQR ===")
print(f"Q1 : {q1}")
print(f"Q3 : {q3}")
print(f"IQR : {iqr}")
print()
print(f"Borne basse : {borne_basse}")
print(f"Borne haute : {borne_haute}")

# Comptage des outliers
outliers = df[(df[col] < borne_basse) | (df[col] > borne_haute)]
print()
print(f"Nombre d'outliers : {len(outliers)}")

=== IQR ===
Q1 : 3.5
Q3 : 19.8
IQR : 16.3

Borne basse : -20.950000000000003
Borne haute : 44.25

Nombre d'outliers : 488

In [25]:
pd.cut(df[col], 10)
pd.qcut(df[col], 10)

0        (15.8, 24.5]
1          (2.7, 4.3]
2          (2.7, 4.3]
3        (15.8, 24.5]
4        (15.8, 24.5]
            ...
5603     (15.8, 24.5]
5604     (15.8, 24.5]
5605       (0.1, 2.7]
5606    (24.5, 40.43]
5607    (-0.001, 0.1]
Name: Emission_GES_kgCO2/m²/an, Length: 5608, dtype: category
Categories (10, interval[float64, right]): [(-0.001, 0.1] < (0.1, 2.7] < (2.7, 4.3] < (4.3, 6.0] ... (10.7, 15.8] < (15.8, 24.5] < (24.5, 40.43] < (40.43, 3125.9]]

In [26]:
pd.cut(df[col], 10).value_counts()

Emission_GES_kgCO2/m²/an
(-3.126, 312.59]      5604
(312.59, 625.18]         1
(1250.36, 1562.95]       1
(1562.95, 1875.54]       1
(2813.31, 3125.9]        1
(625.18, 937.77]         0
(937.77, 1250.36]        0
(1875.54, 2188.13]       0
(2188.13, 2500.72]       0
(2500.72, 2813.31]       0
Name: count, dtype: int64

In [27]:
pd.qcut(df[col], 10).value_counts()

Emission_GES_kgCO2/m²/an
(-0.001, 0.1]      642
(4.3, 6.0]         574
(6.0, 8.0]         567
(40.43, 3125.9]    561
(2.7, 4.3]         560
(10.7, 15.8]       560
(15.8, 24.5]       560
(24.5, 40.43]      558
(8.0, 10.7]        528
(0.1, 2.7]         498
Name: count, dtype: int64